<?php
declare(strict_types=1);

class Business
{
    public function __construct(private PDO $pdo) {}
    public function products(): array { return $this->pdo->query("SELECT * FROM products WHERE status='active' ORDER BY brand, model")->fetchAll(); }
    public function suppliers(): array { return $this->pdo->query("SELECT * FROM suppliers WHERE status='active' ORDER BY name")->fetchAll(); }
    public function customers(): array { return $this->pdo->query("SELECT * FROM customers WHERE status='active' ORDER BY name")->fetchAll(); }
    public function units(string $search = ''): array { $s=$this->pdo->prepare("SELECT u.*, p.brand, p.model, p.variant FROM product_units u INNER JOIN products p ON p.id=u.product_id WHERE u.imei LIKE ? OR p.model LIKE ? ORDER BY u.created_at DESC"); $s->execute(['%'.$search.'%','%'.$search.'%']); return $s->fetchAll(); }
    public function create(string $type, array $data): void {
        $map=['product'=>['products','product_code','PRD','brand,model,variant,color,ram,storage','brand=:brand,model=:model,variant=:variant,color=:color,ram=:ram,storage=:storage'], 'supplier'=>['suppliers','supplier_code','SUP','name,phone,email,address','name=:name,phone=:phone,email=:email,address=:address'], 'customer'=>['customers','customer_code','CUS','name,phone,email,address','name=:name,phone=:phone,email=:email,address=:address']];
        if (!isset($map[$type])) throw new InvalidArgumentException('Data master tidak dikenal.');
        [$table,$codeField,$prefix,$columns]=$map[$type]; $code=$prefix.str_pad((string)($this->pdo->query("SELECT COUNT(*) FROM $table")->fetchColumn()+1),3,'0',STR_PAD_LEFT);
        $fields=explode(',',$columns); $sql="INSERT INTO $table ($codeField,$columns) VALUES (:code,:".implode(',:',$fields).")";
        $statement=$this->pdo->prepare($sql); $statement->execute(['code'=>$code]+array_intersect_key($data,array_flip($fields)));
    }
    public function purchase(array $d): void { $this->pdo->beginTransaction(); try { $amount=(float)$d['purchase_price']; $code='BUY-'.date('Ymd-His'); $s=$this->pdo->prepare('INSERT INTO purchases (purchase_code,supplier_id,purchase_date,total_amount,payment_method,payment_status,created_by) VALUES (?,?,CURDATE(),?,?,?,?)'); $s->execute([$code,$d['supplier_id'],$amount,$d['payment_method'],'paid',$_SESSION['user']['id']]); $purchaseId=(int)$this->pdo->lastInsertId(); $s=$this->pdo->prepare('INSERT INTO product_units (product_id,imei,battery_health,screen_condition,body_condition,completeness,purchase_price,selling_price,status) VALUES (?,?,?,?,?,?,?,?,"available")'); $s->execute([$d['product_id'],$d['imei'],$d['battery_health'] ?: null,$d['screen_condition'] ?: null,$d['body_condition'] ?: null,$d['completeness'] ?: null,$amount,(float)$d['selling_price']]); $unitId=(int)$this->pdo->lastInsertId(); $this->pdo->prepare('INSERT INTO purchase_items (purchase_id,product_unit_id,purchase_price) VALUES (?,?,?)')->execute([$purchaseId,$unitId,$amount]); $this->pdo->prepare('INSERT INTO stock_movements (product_unit_id,movement_type,reference_type,reference_id) VALUES (?,"IN","PURCHASE",?)')->execute([$unitId,$purchaseId]); $this->pdo->commit(); } catch(Throwable $e) { $this->pdo->rollBack(); throw $e; } }
    public function availableUnits(): array { return $this->pdo->query("SELECT u.*, p.brand,p.model,p.variant FROM product_units u INNER JOIN products p ON p.id=u.product_id WHERE u.status='available' ORDER BY p.brand,p.model")->fetchAll(); }
    public function sale(array $d): void { $this->pdo->beginTransaction(); try { $unit=$this->pdo->prepare("SELECT * FROM product_units WHERE id=? AND status='available' FOR UPDATE"); $unit->execute([$d['unit_id']]); $unit=$unit->fetch(); if(!$unit) throw new RuntimeException('Unit tidak tersedia.'); $price=(float)$d['selling_price']; $code='SAL-'.date('Ymd-His'); $s=$this->pdo->prepare('INSERT INTO sales (sale_code,customer_id,sale_date,total_amount,discount,payment_method,payment_status,created_by) VALUES (?,?,CURDATE(),?,?,?,?,?)'); $s->execute([$code,$d['customer_id'],$price,0,$d['payment_method'],'paid',$_SESSION['user']['id']]); $saleId=(int)$this->pdo->lastInsertId(); $profit=$price-(float)$unit['purchase_price']; $this->pdo->prepare('INSERT INTO sale_items (sale_id,product_unit_id,selling_price,profit) VALUES (?,?,?,?)')->execute([$saleId,$unit['id'],$price,$profit]); $this->pdo->prepare("UPDATE product_units SET status='sold',selling_price=? WHERE id=?")->execute([$price,$unit['id']]); $this->pdo->prepare('INSERT INTO stock_movements (product_unit_id,movement_type,reference_type,reference_id) VALUES (?,"OUT","SALE",?)')->execute([$unit['id'],$saleId]); $this->pdo->commit(); } catch(Throwable $e) { $this->pdo->rollBack(); throw $e; } }
    public function report(): array { return $this->pdo->query("SELECT s.sale_code,s.sale_date,c.name AS customer,s.total_amount,COALESCE(SUM(si.profit),0) AS profit FROM sales s INNER JOIN customers c ON c.id=s.customer_id LEFT JOIN sale_items si ON si.sale_id=s.id GROUP BY s.id ORDER BY s.sale_date DESC")->fetchAll(); }
}
